CREATE TABLE MEDICINE (
                          id SERIAL PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          generic_name VARCHAR(255),
                          description TEXT,
                          manufacturer VARCHAR(255) NOT NULL,
                          category VARCHAR(255) NOT NULL,
                          form VARCHAR(100) NOT NULL,
                          dosage VARCHAR(100) NOT NULL,
                          batch_number VARCHAR(100) NOT NULL,
                          expiry_date DATE CHECK (expiry_date > CURRENT_DATE),
                          stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0),
                          reorder_level INTEGER NOT NULL CHECK (reorder_level >= 0),
                          price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
                          purchase_price NUMERIC(10, 2) NOT NULL CHECK (purchase_price > 0),
                          storage_conditions TEXT NOT NULL,
                          prescriptions_required BOOLEAN NOT NULL,
                          controlled_substance BOOLEAN NOT NULL,
                          side_effects TEXT,
                          instructions TEXT,
                          barcode VARCHAR(100),
                          country_of_origin VARCHAR(255) NOT NULL,
                          dosage_unit VARCHAR(50) NOT NULL,
                          contraindications TEXT,
                          interactions TEXT,
                          warnings TEXT
);