apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: healthcare
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare
          image: your-docker-repo/healthcare:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATA_SOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: data-source-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: jwt-secret
            - name: JWT_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: jwt-expiry
            - name: JWT_REFRESH_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: jwt-refresh-expiry
