apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  data-source-url: <base64-encoded-data-source-url>
  db-user: <base64-encoded-db-user>
  db-password: <base64-encoded-db-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-credentials
type: Opaque
data:
  jwt-secret: <base64-encoded-jwt-secret>
  jwt-expiry: <base64-encoded-jwt-expiry>
  jwt-refresh-expiry: <base64-encoded-jwt-refresh-expiry>
